import Link from "next/link";
import Image from "next/image";
import { requireRole } from "@/lib/auth";
import { getCustomerBookings } from "@/lib/bookings";
import { primaryImage, formatAmount } from "@/lib/vehicle-display";
import { BookingStatusBadge } from "@/components/site/booking-status";

export default async function MyBookingsPage() {
  const account = await requireRole("customer");
  let bookings; try { bookings = await getCustomerBookings(account.id); } catch { return <main className="mx-auto flex-1 max-w-5xl px-5 py-12"><p role="alert" className="rounded-xl bg-red-50 p-5 text-red-800">Unable to load your bookings. Refresh and try again.</p></main>; }
  return <main className="mx-auto w-full max-w-5xl flex-1 bg-[#faf9f6] px-5 py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-800">Your account</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">My bookings</h1><p className="mt-2 text-stone-600">Review requests and upcoming journeys.</p></div><Link href="/vehicles" className="rounded-xl bg-emerald-900 px-4 py-3 text-sm font-semibold text-white">Browse vehicles</Link></div><div className="mt-8 space-y-4">{bookings.length ? bookings.map((booking)=>{const image=booking.vehicle ? primaryImage({...booking.vehicle,images:booking.images}) : null; return <article key={booking.id} className="grid gap-5 rounded-2xl border border-stone-200 bg-white p-4 sm:grid-cols-[180px_1fr] sm:p-5"><div className="relative h-40 overflow-hidden rounded-xl bg-stone-100">{image ? <Image src={image} alt={booking.vehicle?.name ?? "Vehicle"} fill sizes="180px" className="object-cover"/>:<div className="grid h-full place-items-center text-xs text-stone-400">No photo</div>}</div><div className="flex flex-col justify-between gap-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-stone-500">{booking.vehicle?.vehicle_type ?? "Rental"}</p><h2 className="mt-1 text-xl font-semibold">{booking.vehicle?.name ?? "Vehicle no longer listed"}</h2><p className="mt-2 text-sm text-stone-600">{booking.pickup_date} — {booking.return_date} · {booking.pickup_location}</p></div><BookingStatusBadge status={booking.status}/></div><div className="flex items-center justify-between border-t border-stone-100 pt-4"><p className="font-semibold">{formatAmount(booking.total_price)} <span className="font-normal text-stone-500">total</span></p><Link href={`/my-bookings/${booking.id}`} className="text-sm font-semibold text-emerald-900">Booking details →</Link></div></div></article>}) : <div className="rounded-2xl border border-dashed border-stone-300 bg-white p-12 text-center"><h2 className="font-semibold">No bookings yet</h2><p className="mt-2 text-sm text-stone-500">Your booking requests will appear here.</p></div>}</div></main>;
}

