"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { createBooking, type BookingActionState } from "@/app/bookings/actions";
import { todayInSriLanka, validDate } from "@/lib/dates";

const initial = {};
export function BookingForm({ vehicleId, price, signedIn, start = "", end = "" }: { vehicleId: string; price: number; signedIn: boolean; start?: string; end?: string }) {
  const [state, action, pending] = useActionState<BookingActionState, FormData>(createBooking, initial);
  const [dates, setDates] = useState({ pickup: validDate(start), returning: validDate(end) });
  const days = dates.pickup && dates.returning && dates.returning > dates.pickup ? Math.round((Date.parse(`${dates.returning}T00:00:00Z`) - Date.parse(`${dates.pickup}T00:00:00Z`)) / 86400000) : 0;
  const money = (amount: number) => `LKR ${new Intl.NumberFormat("en-LK", { maximumFractionDigits: 2 }).format(amount)}`;
  if (!signedIn) return <div className="rounded-2xl bg-stone-50 p-5"><p className="font-semibold">Ready to book?</p><p className="mt-1 text-sm text-stone-600">Sign in or create an account to request this vehicle.</p><Link className="mt-4 inline-flex rounded-xl bg-emerald-900 px-4 py-2.5 text-sm font-semibold text-white" href="/login">Sign in to continue</Link></div>;
  return <form action={action} className="space-y-4"><input type="hidden" name="vehicle_id" value={vehicleId}/><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-stone-600">Pickup date<input required type="date" name="pickup_date" value={dates.pickup} onChange={(e)=>setDates({...dates,pickup:e.target.value})} min={todayInSriLanka()} className="field mt-1"/></label><label className="text-xs font-semibold text-stone-600">Return date<input required type="date" name="return_date" value={dates.returning} onChange={(e)=>setDates({...dates,returning:e.target.value})} min={dates.pickup || todayInSriLanka()} className="field mt-1"/></label></div>{days>0&&<div className="rounded-xl bg-stone-50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-stone-500">Estimated total</p><div className="mt-2 flex justify-between text-sm"><span>{money(price)} × {days} {days===1?"day":"days"}</span><span className="font-semibold">{money(price*days)}</span></div><p className="mt-2 text-xs text-stone-500">Your dates and final price are rechecked before the request is saved.</p></div>}<label className="block text-xs font-semibold text-stone-600">Pickup location<input required minLength={2} maxLength={160} name="pickup_location" placeholder="City or preferred collection point" className="field mt-1"/></label><label className="block text-xs font-semibold text-stone-600">Notes <span className="font-normal">(optional)</span><textarea name="notes" maxLength={1000} rows={3} placeholder="Anything we should know?" className="field mt-1"/></label>{state.error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>}<p className="text-xs leading-5 text-stone-500">Your request starts as pending. The rental team will confirm it.</p><button disabled={pending} className="w-full rounded-xl bg-emerald-900 px-4 py-3 font-semibold text-white hover:bg-emerald-800 disabled:opacity-50">{pending ? "Checking availability…" : "Check dates & request booking"}</button></form>;
}
